export const cars = [
    // template
    // {
    //     thumbnail: "images/.jpg",
    //     rankOverall: ,
    //     carType: "",
    //     name: "",
    //     make: "",
    //     reliability: ,
    //     safety: ,
    //     cost: ,
    //     comfort: ,
    //     fuelEfficiency: ,
    //     price: ,
    //     isLiked: false,
    //     uuid: "",
    // },
    {
        thumbnail: "images/camry.jpg",
        rankOverall: 1,
        rankInCategory: 1,
        carType: "Sedan",
        name: "Toyota Camry",
        make: "Toyota",
        reliability: 4.5, 
        safety: 4.0, 
        price: 3.5, 
        comfort: 4.0, 
        fuelEfficiency: 4.0,
        price: "MSRP $25,965",
        isLiked: false,
        uuid: "6dcb2d27-3c92-4a27-8ba9-93af9a9d1b2e",
    },
    {
        thumbnail: "images/accord.jpg",
        rankOverall: 2,
        rankInCategory: 2,
        carType: "Sedan",
        name: "Honda Accord",
        make: "Honda",
        reliability: 4.0, 
        safety: 4.5, 
        price: 3.5, 
        comfort: 4.0, 
        fuelEfficiency: 4.0,
        price: "MSRP $21,700",
        isLiked: false,
        uuid: "39d93de1-0f07-47f7-bc87-08101a9d7049",
    },
    {
        thumbnail: "images/civic.jpg",
        rankOverall: 3,
        rankInCategory: 3,
        carType: "Sedan",
        name: "Honda Civic",
        make: "Honda",
        reliability: 4.0, 
        safety: 4.5, 
        price: 3.5, 
        comfort: 3.5, 
        fuelEfficiency: 4.5,
        price: "MSRP $25,965",
        isLiked: false,
        uuid: "63eaf581-39f5-4d25-bb90-c36911f63fa0",
    },
    {
        thumbnail: "images/corolla.jpg",
        rankOverall: 4,
        rankInCategory: 4,
        carType: "Sedan",
        name: "Toyota Corolla",
        make: "Toyota",
        reliability: 4.5, 
        safety: 4.0, 
        price: 3.5, 
        comfort: 3.5, 
        fuelEfficiency: 4.5,
        price: "MSRP $20,025",
        isLiked: false,
        uuid: "772d4b4f-4916-4d6a-9c3f-d31999b0c48b",
    },
    {
        thumbnail: "images/rav4.jpg",
        rankOverall: 5,
        rankInCategory: 1,
        carType: "SUV",
        name: "Toyota RAV4",
        make: "Toyota",
        reliability: 4.5, 
        safety: 4.5, 
        price: 3.5, 
        comfort: 3.5, 
        fuelEfficiency: 4.0,
        price: "MSRP $26,150",
        isLiked: false,
        uuid: "9ab3d684-354c-42e3-a738-16f98d233977",
    },
    {
        thumbnail: "images/crv.jpg",
        rankOverall: 6,
        rankInCategory: 2,
        carType: "SUV",
        name: "Honda CR-V",
        make: "Honda",
        reliability: 4.0, 
        safety: 4.5, 
        price: 3.5, 
        comfort: 4.0, 
        fuelEfficiency: 4.0,
        price: "MSRP $26,925",
        isLiked: false,
        uuid: "b97a17a9-9fc9-4fc8-9a13-7105a334b7e5",

    },
    {
        thumbnail: "images/cx5.jpg",
        rankOverall: 7,
        rankInCategory: 3,
        carType: "SUV",
        name: "Mazda CX-5",
        make: "Mazda",
        reliability: 4.0, 
        safety: 4.5, 
        price: 4.0, 
        comfort: 4.0, 
        fuelEfficiency: 4.0,
        price: "MSRP $25,370",
        isLiked: false,
        uuid: "c4547a77-2b1f-4a8a-a29a-f0b475ee0d22",
    },
    {
        thumbnail: "images/silverado.jpg",
        rankOverall: 8,
        rankInCategory: 1,
        carType: "Truck",
        name: "Chevrolet Silverado 1500",
        make: "Chevrolet",
        reliability: 4.0,
        safety: 4.5,
        cost: 3.5,
        comfort: 4.0,
        fuelEfficiency: 3.5,
        price: "MSRP $30,995",
        isLiked: false,
        uuid: "e248bb28-5b1f-4285-9ed5-5b58f84b7a15",
    },
    {
        thumbnail: "images/outback.jpg",
        rankOverall: 9,
        rankInCategory: 4,
        carType: "SUV",
        name: "Subaru Outback",
        make: "Subaru",
        reliability: 4.5,
        safety: 4.7,
        cost: 4.2,
        comfort: 4.0,
        fuelEfficiency: 4.6,
        price: "MSRP $27,845",
        isLiked: false,
        uuid: "f0a2a79b-5dc7-4849-bd9f-b2e4411ed260",
    },
    {
        thumbnail: "images/f150.jpg",
        rankOverall: 10,
        rankInCategory: 2,
        carType: "Truck",
        name: "Ford F-150",
        make: "Ford",
        reliability: 4.5,
        safety: 4.5,
        cost: 3.5,
        comfort: 4.5,
        fuelEfficiency: 3.5,
        price: "MSRP $28,940",
        isLiked: false,
        uuid: "085ebdcf-1fbf-42e5-a7f4-4adad67f4a4b",
    },
    {
        thumbnail: "images/rx.jpg",
        rankOverall: 12,
        rankInCategory: 2 ,
        carType: "SUV",
        name: "Lexus RX",
        make: "Lexus",
        reliability: 4.7,
        safety: 4.7,
        cost: 3.5,
        comfort: 4.7,
        fuelEfficiency: 3.5,
        price: "MSRP $46,000",
        isLiked: false,
        uuid: "2a07d3d3-6cfc-4a0f-bef4-02f37eb4e317",
    },
    
]
